# Generated by Django 4.1.4 on 2023-04-27 22:17

import django.core.validators
from django.db import migrations, models
import film.path_film.get_path_upload_cover_image
import film.permissions.image


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieshots',
            name='image',
        ),
        migrations.AddField(
            model_name='movieshots',
            name='count_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movieshots',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=film.path_film.get_path_upload_cover_image.get_path_upload_cover_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg']), film.permissions.image.validate_size_image]),
        ),
    ]
